version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/beego-search-server"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/gingonic-search-server"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/search-bot/linux-search-bot"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/search-bot/windows-search-bot"
    schedule:
      interval: "daily"
