version: 2
updates:
  - package-ecosystem: "gomod"
    directory:
      - "/beego-search-server"
      - "/gingonic-search-server"
      - "/search-bot/linux-search-bot"
      - "/search-bot/windows-search-bot"
    schedule:
      interval: "daily"
